import Head from 'next/head'
import TodoList from './TodoList'
import TodoForm from './TodoForm'

export default function Home() {
  
  return (
    <div className="container">
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main">
        <h1>Todo App</h1>
        <TodoForm/>
        <TodoList/>
      </div>
    </div>
  )
}
